### ISSUE TITLE
[BUG] EWW! I FOUND A BUG

### ISSUE THREAD

**Issue by turnerlux** [Strip3s/PhoenixBot#107]
I am getting these errors and Best Buys not letting me sign in and making me reset my password when I go back to regular browser. 

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 90.0.4430
[WDM] - Get LATEST driver version for 90.0.4430
[WDM] - Driver [C:\Users\Turner\.wdm\drivers\chromedriver\win32\90.0.4430.24\chromedriver.exe] found in cache

DevTools listening on ws://127.0.0.1:57169/devtools/browser/12ce59d4-ce56-4ff0-9076-c340fddd9a57
[2021-04-03 21:17:29][TASK 1] Starting Best Buy Task
[2021-04-03 21:17:30][TASK 1] PDP Request: 200
[2021-04-03 21:17:30][TASK 1] Product URL: https://www.bestbuy.com/site/nvidia-geforce-rtx-3070-8gb-gddr6-pci-express-4-0-graphics-card-dark-platinum-and-black/6429442.p?cmp=RMX&skuId=6429442
[2021-04-03 21:17:30][TASK 1] Product URL Request: 200
[2021-04-03 21:17:30][TASK 1] Loading headless driver.
[2021-04-03 21:17:30][TASK 1] Loading https://www.bestbuy.com/
[2021-04-03 21:17:30][TASK 1] Logging in...
[9464:29608:0403/211733.195:ERROR:device_event_log_impl.cc(214)] [21:17:33.195] USB: usb_device_handle_win.cc:1054 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[9464:29608:0403/211733.196:ERROR:device_event_log_impl.cc(214)] [21:17:33.196] Bluetooth: bluetooth_adapter_winrt.cc:1072 Getting Default Adapter failed.
Traceback (most recent call last):
  File "C:\Users\Turner\Desktop\PhoenixBot-master\pages\homepage.py", line 510, in run
    BestBuy(self.status_signal, self.image_signal, self.product, profile, proxy, self.monitor_delay, self.error_delay) #TODO: Readd Discord Webhook
  File "C:\Users\Turner\Desktop\PhoenixBot-master\sites\bestbuy.py", line 102, in __init__
    self.login()
  File "C:\Users\Turner\Desktop\PhoenixBot-master\sites\bestbuy.py", line 156, in login
    WebDriverWait(self.browser, 10).until(
  File "C:\Users\Turner\AppData\Local\Programs\Python\Python39-32\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

[9464:29608:0403/211743.914:ERROR:device_event_log_impl.cc(214)] [21:17:43.915] Bluetooth: bluetooth_adapter_winrt.cc:1072 Getting Default Adapter failed.
[25296:7716:0403/211929.117:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is disabled

**Comment by jack60612** [comment]
@turnerlux  most of those errors are from usb devices. try again with the newest version of phoenix bot
