### ISSUE TITLE
[BUG] EWW! I FOUND A BUG

### ISSUE THREAD

**Issue by saltnpixels** [Strip3s/PhoenixBot#38]
Trying this on a mac and cant get it working.... I'm a front end developer so this is beyond me a bit...

error:
```
~/Documents/PhoenixBot master*
❯ python3 app.py             
Traceback (most recent call last):
  File "/Users/ericgreenfield/Documents/PhoenixBot/app.py", line 2, in <module>
    from pages.homepage import HomePage,TaskTab
  File "/Users/ericgreenfield/Documents/PhoenixBot/pages/homepage.py", line 2, in <module>
    from sites.walmart import Walmart
  File "/Users/ericgreenfield/Documents/PhoenixBot/sites/walmart.py", line 1, in <module>
    from sites.walmart_encryption import walmart_encryption as w_e
  File "/Users/ericgreenfield/Documents/PhoenixBot/sites/walmart_encryption.py", line 5, in <module>
    from js2py.pyjs import *
ModuleNotFoundError: No module named 'js2py'
```

I tried finding and installing with brew the js2py... it doesnt exist?

**Comment by saltnpixels** [comment]
I think I'm understanding a bit more...
when I tired to install the requirements i got a bug

```
 ERROR: Command errored out with exit status 1:
     command: /Users/ericgreenfield/Documents/PhoenixBot/env/bin/python3 /Users/ericgreenfield/Documents/PhoenixBot/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/tmp0rtnm8ge
         cwd: /private/var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/pip-install-jond_aqz/pyqt5
    Complete output (31 lines):
    Traceback (most recent call last):
      File "/Users/ericgreenfield/Documents/PhoenixBot/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
```

**Comment by Strip3s** [comment]
> I think I'm understanding a bit more...
> 
> when I tired to install the requirements i got a bug
> 
> 
> 
> ```
> 
>  ERROR: Command errored out with exit status 1:
> 
>      command: /Users/ericgreenfield/Documents/PhoenixBot/env/bin/python3 /Users/ericgreenfield/Documents/PhoenixBot/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/tmp0rtnm8ge
> 
>          cwd: /private/var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/pip-install-jond_aqz/pyqt5
> 
>     Complete output (31 lines):
> 
>     Traceback (most recent call last):
> 
>       File "/Users/ericgreenfield/Documents/PhoenixBot/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 126, in prepare_metadata_for_build_wheel
> 
>         hook = backend.prepare_metadata_for_build_wheel
> 
>     AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
> 
> ```

I think this is just a requirement issue. Just remove the version from the requirements.Txt for pyqt and try seeing what happens

**Comment by saltnpixels** [comment]
I did that before. Still didn't work.

**Comment by saltnpixels** [comment]
I tried installing any module missing and it says:

```
 Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/ericgreenfield/Documents/PhoenixBot/env/bin/python3 /Users/ericgreenfield/Documents/PhoenixBot/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/tmp91230bbx
         cwd: /private/var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/pip-install-ehgo3bhi/pyqt5
    Complete output (31 lines):
    Traceback (most recent call last):
      File "/Users/ericgreenfield/Documents/PhoenixBot/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/ericgreenfield/Documents/PhoenixBot/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/Users/ericgreenfield/Documents/PhoenixBot/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/ericgreenfield/Documents/PhoenixBot/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 130, in prepare_metadata_for_build_wheel
        return _get_wheel_metadata_from_wheel(backend, metadata_directory,
      File "/Users/ericgreenfield/Documents/PhoenixBot/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 159, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/private/var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/pip-build-env-jccoyerw/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/private/var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/pip-build-env-jccoyerw/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 82, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/private/var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/pip-build-env-jccoyerw/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 479, in setup
        self.apply_user_defaults(tool)
      File "project.py", line 64, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/private/var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/pip-build-env-jccoyerw/overlay/lib/python3.8/site-packages/pyqtbuild/project.py", line 89, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/private/var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/pip-build-env-jccoyerw/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 225, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/private/var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/pip-build-env-jccoyerw/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 68, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/ericgreenfield/Documents/PhoenixBot/env/bin/python3 /Users/ericgreenfield/Documents/PhoenixBot/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/tmp91230bbx Check the logs for full command output.
```

**Comment by gr33k** [comment]
I assume you've tried:
pip3 install js2py

I have mine here:
Requirement already satisfied: js2py in /usr/local/lib/python3.9/site-packages (0.68)

**Comment by Jbibianochavez** [comment]
Hello guys, I'm new but have quite a bit of python experience. I looked into the old bird bot code and fixed it enough to run on Walmart, then I ran into this repo. I had into a similar situation and it ended up being an issue with my environment. My /usr/local/bin had python3, Python 3.8, and python 3.9 same for pip3. When I tried the command pip3 install pyqt (in my case) I would get the same error you are getting. When I tried pip3.8 it worked, I was also able run the bot with the python3.8 command. After doing some research I found this might be attributed to an incompatibility issue with the pip version and the library, I did not continue my research since I found a work around. Also, I am not sure if JS2PY is available via home brew, but I know pyqt is, so that was an alternative. Another option is starting a python virtual environment with a fresh version of python to avoid any incompatibility or messing with your main environment. I might have been running into a different issue but maybe this will help someone who comes across this thread.
